### ISSUE TITLE
Probably a long shot, but is this project still have developer visibility?

### ISSUE THREAD

**Issue by khillabolt** [greystate/xslt-tmbundle#1]
Hi there, as an avid Textmate2 and XML/XSLT developer, I'm quite smitten with this Bundle and all of the shortcuts it offers.

Curious though, I'm guess you've long moved on, but I wondering if any of the files mentioned here "Some commands still refer to scripts on my local drive, so won't work. Hopefully I'll be able to fix those along the way." may still be available some where..

Specifically I'd love to see what you had here:

- ${TM_SUPPORT_PATH}/lib/bash_init.sh
- /Users/chriz/Development/Misc/XSLT/xml-structure.xsl
- /Users/chriz/Development/Misc/XSLT/namespace-transform.xsl

**Comment by greystate** [comment]
Hi @khillabolt  -  thank you for stopping by 👍 

I'll just fling the files in here so you can grab 'em by their bits:

[missing-bits.zip](https://github.com/greystate/xslt-tmbundle/files/2587256/missing-bits.zip)

The `bash_init.sh` file I have never touched myself (atleast not on purpose) so should be pretty much vanilla/pristine (unless TM2 modifies it regularly).

There's a couple of CSS files that are referenced by the resulting files from the transforms.

Let me know if there's anything you want to know about this, or if there are other files missing!

/Chriztian

**Comment by khillabolt** [comment]
Oh my! thank you Chriztian.. have to admit, I thought it was a long shot anyone would reply.. 😃 

I've forked your project my my own github.. Hopefully to make a few tweaks and verify all things are still working with the most recent version of TM2 (since it's been round and round development wise). Maybe a PR back .. eventually .. 👍 

Thanks again.. Have a good one.

**Comment by greystate** [comment]
FYI I just pushed a branch with the current state of the bundle on my disk, just in case there's something you'll find useful. I still use it a lot but had never thought to push anything this way :)
